name: Delete PDF Files

on:
  workflow_dispatch:  # يمكن تشغيله يدويًا من واجهة GitHub

jobs:
  delete-pdfs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Delete all PDF files
        run: |
          find . -type f -iname "*.pdf" -exec rm -f {} \;

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -u
          git commit -m "GitHub Action: حذف جميع ملفات PDF تلقائيًا" || echo "No changes to commit"
          git push
